name: Check for New RoboMaster Articles

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  check_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # --- THIS IS THE NEW, MORE RELIABLE STEP ---
      # This action installs a fresh version of Google Chrome and all its dependencies.
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      
      # We no longer need the manual apt-get install step.

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run the monitor
        env:
          DJI_USERNAME: ${{ secrets.DJI_USERNAME }}
          DJI_PASSWORD: ${{ secrets.DJI_PASSWORD }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        # The 'run' command now happens after Chrome is fully set up.
        run: go run main.go