name: Check for New RoboMaster Articles

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  check_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # --- THIS IS THE NEW, REQUIRED STEP ---
      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 libappindicator1 libindicator7 libgtk-3-0 libasound2 libnspr4 libnss3 xdg-utils fonts-liberation

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run the monitor
        env:
          DJI_USERNAME: ${{ secrets.DJI_USERNAME }}
          DJI_PASSWORD: ${{ secrets.DJI_PASSWORD }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: go run main.go
        